# Generated by Django 2.1.1 on 2018-09-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=8)),
                ('savings', models.DecimalField(decimal_places=2, max_digits=8)),
                ('start_of_pay', models.DateField()),
                ('frequency_of_pay', models.IntegerField()),
            ],
        ),
    ]
